const C = {
	CREATE_COMPANY: 'CREATE_COMPANY',
	FETCH_COMPANIES: 'FETCH_COMPANIES',
	CREATE_OFFICE: 'CREATE_OFFICE',
	FETCH_OFFICES: 'FETCH_OFFICES',
	GET_COMPANY: 'GET_COMPANY',
	CLOSE_MODAL: 'CLOSE_MODAL',
	OPEN_MODAL: 'OPEN_MODAL'
};

export default C;
